# Generated by Django 5.1.2 on 2024-10-22 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../cat_h31tct', upload_to='images/')),
                ('image_filter', models.CharField(choices=[('_2000', '2000'), ('selfie', 'Selfie'), ('holidays', 'Holidays'), ('summer', 'Summer'), ('hiking', 'Hiking'), ('dinner', 'Dinner'), ('happiness', 'Happiness'), ('winter', 'Winter'), ('family', 'Family'), ('sunshine', 'Sunshine'), ('wild', 'Wild'), ('rome', 'Rome'), ('beauty', 'Beauty'), ('work', 'Work')], default='normal', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
